Level 1
AleksandrStamat/movies-explorer-api pull request #1
Opened 2021-04-14 19:06 UTC by AleksandrStamat

Сделал бэкенд для диплома на проверку 
Публичный IPv4: 178.154.205.44
Домен: https://api.movies.stamat.nomoredomains.icu/

2021-04-16 11:59 UTC, zlocate commented
# Резюме:
## Backend

### Критерии, влияющие на работоспособность
- [ ] <!--3.64--> В репозитории есть все необходимые инфраструктурные файлы:
  - [ ] в проекте есть package.json;
    В списке зависимостей присутствует неиспользуемый модуль cookie-parser.
  - [x] .editorconfig;
  - [x] .eslintrc, расширяющий конфигурацию airbnb-base, а также необходимые для работы линтера dev-зависимости;
  - [x] .gitignore.
  - [x] в .eslintrc добавлено исключение для _id;
- [ ] <!--3.64--> При выполнении команды npx eslint . ошибки линтинга должны отсутствовать.
  В дипломном проекте запрещается переопределять правила линтера кроме no-underscore-dangle
  https://i.imgur.com/6YK5Om7.png
- [x] <!--3.64--> В разделе scripts файла package.json:
  - [x] есть команда npm run start, которая запускает сервер на localhost:3000;
  - [x] и npm run dev, которая запускает сервер на localhost:3000 с хот релоудом.
- [x] <!--12.57--> Когда все зависимости установлены, приложение запускается командой npm run dev без ошибок.
- [ ] <!--25.45--> Описанные роуты работают корректно:
  - [ ] запрос на `GET /users/me` возвращает информацию о пользователе (email и имя);
    Метод возвращает ошибку со статус-кодом 404 - https://i.imgur.com/5VAfgxJ.png
    Id пользователя должен браться из сессии, а не передаваться в виде параметра
  - [ ] `PATCH /users/me` — обновляет информацию о пользователе;
    В .catch-блоке в случае выпадения ошибки NotFoundError сервис возвращает ошибку со статус-кодом 400, сто некорректно - т.к NotFoundError говорит о том, что пользователь не был найден, а следовательно статус-код должен быть 404.
    Кроме того, в данном методе нет кода который может выбросить данное исключение - т.е мы никогда не попадем в данную ветку, поэтому данный фрагмент следует исключить
  - [ ] `GET /movies` — все сохранённые пользователем фильмы;
    Метод не должен возвращать поле owner в результате операции - https://i.imgur.com/PEa7sVj.png
  - [ ] `POST /movies` — создаёт фильм с переданными в теле данными;
    Метод не должен возвращать поле owner в результате операции - https://i.imgur.com/24p7vgG.png

    Для создания фильма необходимо использовать метод create, вместо обновления несуществующего фильма с флагом создавать новый объект если фильм не найден.
    https://i.imgur.com/DyHOvr5.png
  - [ ] `DELETE /movies/movieId` — удаляет сохранённый фильмы по `_id`;
    Необходимо разделять случаи когда карточка есть, но она принадлежит другому пользователю (403) и когда карточки нет в БД (404)
    Сейчас сервис в любом случае возвращает ошибку 404
  - [ ] `POST /signup` — создаёт пользователя с переданными в теле данными;
  - [ ] `POST /signin` — возвращает JWT, если в теле запроса переданы правильные почта и пароль.
    Ошибка захардкожена - вне зависимости от того какая фактически ошибка произойдет будет возвращена 401я, что некорректно.
    https://i.imgur.com/KsQkQsK.png
    Я рекомендую перенсти выброс исключения в метод логина на уровне модели а в данном местоте просто пробрасывать ошибки при помощи next(err)
    Благодаря этому вы избавитесь от харкода и необходимости проверять тип ошибки в самом методе
  - [x] Если вы сохраняете JWT в куках, роут `/signout` должен удалять JWT из куки.
- [x] <!--3.64--> Все роуты, кроме /signin и /signup, защищены авторизацией.
  Мидлвара для обработки неизвестного маршрута не закрыта авторизацией. Критерий засчитываю, но прошу исправить этот момент
- [x] <!--3.64--> Роуты пользователей и роуты фильмов описаны в отдельных файлах.
- [x] <!--3.64--> Ошибки API обрабатываются:
  - [x] если в запросе что-то не так, сервер возвращает ответ с ошибкой и её статусом;
  - [x] асинхронные обработчики завершены блоком catch;
  - [x] API не возвращает стандартных ошибок базы данных или Node.js.
- [x] <!--3.64--> В production-режиме адрес базы данных берётся из process.env.
- [x] <!--3.64--> Реализовано бережное хранение пароля:
  - [x] пароль хранится в зашифрованном виде;
  - [x] API не возвращает хеш пароля клиенту.
- [ ] <!--3.64--> Данные валидируются перед добавлением в базу.
  Для полей некорректно задано требование обязательно на уровне модели.
  Вместо requited флаг называется require из-за чего потенциально возможно не задавать какое-либо из полей
  Для демонстрации проблемы отключите схему Joi для метода создания фильма и попробуйте создать фильм, не передавая поле year
  https://i.imgur.com/ct7s62n.png
  Фильм создастся корректно
  Та же самая проблема есть и для модели пользователя
- [x] <!--3.64--> Пользователь не может удалить сохранённую карточку из профиля другого пользователя.
- [x] <!--3.64--> К серверу можно обратиться по https по адресу домена, указанному в README.md. 
- [x] <!--3.64--> Правильно реализовано хранение секретного ключа для создания JWT:
  - [x] для продакшн сборки он хранится в .env файле — этот файл не добавляется в git;
  - [x] в режиме разработки (при process.env.NODE_ENV !== 'production') код запускается и работает и без .env файла.

### Хорошие практики
- [x] <!--1.5--> Асинхронные операции реализованы промисами или async/await.
- [ ] <!--1.5--> Запрос валидируется перед передачей контроллеру. Тело и, где необходимо, заголовки и параметры, проверяются по соответствующим схемам. Если запрос не соответствует схеме, обработка не передаётся контроллеру, и клиент получает ошибку валидации.
  В задании отсутствует ограничение на длину пароля
  Флаг unknown:true приводит к тому что валидацию проходят запросы содержащие произвольные дополнительные поля и эти запросы попадают в контроллер, что некорректно в рамках нашей работы
  Флаг unknown:true предназначен для случаев когда точно определить формат запроса не возможно (клиент может добавить произвольные поля) исходя из бизнес-логики приложения.
  Это не наш случай :)
- [ ] <!--1.5--> Настроено логгирование:
  - [x] запросы и ответы записываются в файл request.log;
  - [ ] ошибки записываются в файл error.log;
    В лог-файл не логгируется текст ошибки
    https://i.imgur.com/pJQ67PQ.png
    Это происходит потому, что вы передаете в объект ошибки вместо текста объект
  - [x] файлы логов не добавляются в репозиторий.
- [x] <!--1.5--> Ошибки обрабатываются централизованным обработчиком.
- [ ] <!--1.5--> Централизованный обработчик ошибок описан в отдельном модуле.
  Описан в app.js
- [ ] <!--1.5--> В случае ошибки API возвращает статус ответа, который соответствует типу ошибки.
  Необходимо разделять случаи когда при удалении карточка есть, но она принадлежит другому пользователю (403) и когда карточки нет в БД (404)
  Сейчас сервис в любом случае возвращает ошибку 404
- [x] <!--1.5--> К серверу можно обратиться по https по адресу домена, указанному в README.md.
- [x] <!--1.5--> API приложения располагается на домене вида: name.zone/api, а не просто name.zone
- [ ] <!--1.5--> Все роуты подключены в файле index.js, который находится в папке routes. Оттуда единый роут подключается в файле app.js.
  Роут для /crash-test описан в app.js
### Рекомендации
- [x] <!--0.83--> Для ошибок API созданы классы, расширяющие конструктор Error.
- [x] <!--0.83--> Используется модуль Helmet для установки заголовков, связанных с безопасностью.
- [ ] <!--0.83--> Конфигурация и константы в отдельных файлах:
  - [ ] адрес Mongo-сервера в режиме разработки вынесен в отдельный конфигурационный файл;
    Соджится в app.js
  - [ ] константы приложения — сообщения ответов и ошибок — вынесены в отдельный файл с константами.
    Сообщения об ошибках не вынесены во внешний файл с константами
    https://i.imgur.com/ogqF6Bq.png
    На скриншоте 2 примера, фактически их больше. Также необходимо вынести во внешний файл тексты ошибок валидации Joi и валидаторов на уровне модели данных.
- [x] <!--0.83--> Настроен rate limiter: число запросов с одного IP в единицу времени ограничено.
- [x] <!--0.83--> rate limiter сконфигурирован в отдельном файле и импортируется в app.js
- [x] <!--0.83--> API размещено на отдельном поддомене, например: api.news-explorer.tk.

## Количество баллов: 55


## Дом комментари:
- Сервис [...]

2021-04-18 09:57 UTC, vrnsky commented on .editorconfig
> +# Possible values - tab, space
If you code require comment. It is bad code

2021-04-18 09:58 UTC, vrnsky commented on errors/ConflictError.js
> +    this.status = 409;
Good practice! I will give you five out of five of using correct HTTP code

2021-04-18 10:00 UTC, vrnsky commented on models/movie.js
> +    require: [true, 'Поле "country" обязательно для заполнения.'],
Localization friend, you should care about user about other countries

2021-04-18 10:01 UTC, vrnsky commented on models/user.js
> +// const isLength = require('validator/lib/isLength');
Why is it here?? If you don't need this remove this, if need uncomment. In other case, you have git to restore git history

2021-04-18 10:02 UTC, vrnsky requested changes
1. Add CI/CD tools
2. Remove commented code which is not used
3. Where is UNIT and INTEGERATION test??!

2021-04-18 10:02 UTC, vrnsky commented on models/user.js
> +    required: [true, 'Поле "password" обязательно для заполнения.'],
It's will be working only for Russian users

2021-04-21 14:04 UTC, AleksandrStamat commented
прошу проверить работу поскорее

2021-04-21 19:44 UTC, zlocate commented
Добрый вечер.

# Резюме:
## Backend

### Критерии, влияющие на работоспособность
- [x] <!--3.64--> В репозитории есть все необходимые инфраструктурные файлы:
  - [x] в проекте есть package.json;
  - [x] .editorconfig;
  - [x] .eslintrc, расширяющий конфигурацию airbnb-base, а также необходимые для работы линтера dev-зависимости;
  - [x] .gitignore.
  - [x] в .eslintrc добавлено исключение для _id;
- [x] <!--3.64--> При выполнении команды npx eslint . ошибки линтинга должны отсутствовать.
- [x] <!--3.64--> В разделе scripts файла package.json:
  - [x] есть команда npm run start, которая запускает сервер на localhost:3000;
  - [x] и npm run dev, которая запускает сервер на localhost:3000 с хот релоудом.
- [x] <!--12.57--> Когда все зависимости установлены, приложение запускается командой npm run dev без ошибок.
- [ ] <!--25.45--> Описанные роуты работают корректно:
  - [x] запрос на `GET /users/me` возвращает информацию о пользователе (email и имя);
  - [ ] `PATCH /users/me` — обновляет информацию о пользователе;
    В случае, если в метод обновления профиля переданы неполные данные, например отсутствует поле name сервис возращает 500ю ошибку 
    https://i.imgur.com/O5yE3bY.png

    Ошибка валидации уникальности может возникнуть не только в методе регистрации, но и в методе обновления профиля, в случае когда в него передается email, который уже есть в БД.
    Как воспроизвести - зарегистрировать 2 пользователей с email: some1@ya.ru и some2@ya.ru, авторизоваться с учеткой some2@ya.ru и передать в метод обновления профиля some1@ya.ru
    Необходимо в данном случае возвращать ошибку со статус-кодом 409
  - [x] `GET /movies` — все сохранённые пользователем фильмы;
  - [x] `POST /movies` — создаёт фильм с переданными в теле данными;
  - [x] `DELETE /movies/movieId` — удаляет сохранённый фильмы по `_id`;
  - [x] `POST /signup` — создаёт пользователя с переданными в теле данными;
  - [x] `POST /signin` — возвращает JWT, если в теле запроса переданы правильные почта и пароль.
  - [x] Если вы сохраняете JWT в куках, роут `/signout` должен удалять JWT из куки.
- [x] <!--3.64--> Все роуты, кроме /signin и /signup, защищены авторизацией.

  Мидлвара для обработки неизвестного маршрута не закрыта авторизацией. Критерий засчитываю, но прошу исправить этот момент

- [x] <!--3.64--> Роуты пользователей и роуты фильмов описаны в отдельных файлах.
- [x] <!--3.64--> Ошибки API обрабатываются:
  - [x] если в запросе что-то не так, сервер возвращает ответ с ошибкой и её статусом;
  - [x] асинхронные обработчики завершены блоком catch;
  - [x] API не возвращает стандартных ошибок базы данных или Node.js.
- [x] <!--3.64--> В production-режиме адрес базы данных берётся из process.env.
- [x] <!--3.64--> Реализовано бережное хранение пароля:
  - [x] пароль хранится в зашифрованном виде;
  - [x] API не возвращает хеш пароля клиенту.
- [x] <!--3.64--> Данные валидируются перед добавлением в базу.
- [x] <!--3.64--> Пользователь не может удалить сохранённую карточку из профиля другого пользователя.
- [x] <!--3.64--> К серверу можно обратиться по https по адресу домена, указанному в README.md. 
- [x] <!--3.64--> Правильно реализовано хранение секретного ключа для создания JWT:
  - [x] для продакшн сборки он хранится в .env файле — этот файл не добавляется в git;
  - [x] в режиме разработки (при process.env.NODE_ENV !== 'production') код запускается и работает и без .env файла.

### Хорошие практики
- [x] <!--1.5--> Асинхронные операции реализованы промисами или async/await.
- [ ] <!--1.5--> Запрос валидируется перед передачей контроллеру. Тело и, где необходимо, заголовки и параметры, проверяются по соответствующим схемам. Если запрос не соответствует схеме, обработка не передаётся контроллеру, и клиент получает ошибку валидации.
 
  В задании отсутствует ограничение на длину пароля
 
  Joi пропускает запросы содержащие неполные данные в контроллер метода обновления профиля - https://i.imgur.com/O5yE3bY.png
- [ ] <!--1.5--> Настроено логгирование:
  - [x] запросы и ответы записываются в файл request.log;
  - [ ] ошибки записываются в файл error.log;
    В лог-файл не логгируется текст ошибки
    https://i.imgur.com/pJQ67PQ.png
    Это происходит потому, что вы передаете в объект ошибки вместо текста объект
  - [x] файлы логов не добавляются в репозиторий.
- [x] <!--1.5--> Ошибки обрабатываются централизованным обработчиком.
- [ ] <!--1.5--> Централизованный обработчик ошибок описан в отдельном модуле.
  Описан в app.js
- [x] <!--1.5--> В случае ошибки API возвращает статус ответа, который соответствует типу ошибки.
- [x] <!--1.5--> К серверу можно обратиться по https по адресу домена, указанному в README.md.
- [x] <!--1.5--> API приложения располагается на домене вида: name.zone/api, а не просто name.zone
- [x] <!--1.5--> Все роуты подключены в файле index.js, который находится в папке routes. Оттуда единый роут подключается в файле app.js.
### Рекомендации
- [x] <!--0.83--> Для ошибок API созданы классы, расширяющие конструктор Error.
- [x] <!--0.83--> Используется модуль Helmet для установки заголовков, связанных с безопасностью.
- [ ] <!--0.83--> Конфигурация и константы в отдельных файлах:
  - [x] адрес Mongo-сервера в режиме разработки вынесен в отдельный конфигурационный файл;
  - [ ] константы приложения — сообщения ответов и ошибок — вынесены в отдельный файл с константами.
    Тексты ошибок валидации на уровне запросов и БД не вынесены во внешний файл
    https://i.imgur.com/pN618qM.png
    https://i.imgur.com/pxKTmxL.png
- [x] <!--0.83--> Настроен rate limiter: число запросов с одного IP в единицу времени ограничено.
- [x] <!--0.83--> rate limiter сконфигурирован в отдельном файле и импортируется в app.js
- [x] <!--0.83--> API размещено на отдельном поддомене, например: api.news-explorer.tk.

## Количество баллов: 69

2021-04-22 11:37 UTC, AleksandrStamat commented
Отправляю на 3-е ревью!

2021-04-23 09:50 UTC, zlocate commented
# Резюме:
## Backend

### Критерии, влияющие на работоспособность
- [x] <!--3.64--> В репозитории есть все необходимые инфраструктурные файлы:
  - [x] в проекте есть package.json;
  - [x] .editorconfig;
  - [x] .eslintrc, расширяющий конфигурацию airbnb-base, а также необходимые для работы линтера dev-зависимости;
  - [x] .gitignore.
  - [x] в .eslintrc добавлено исключение для _id;
- [x] <!--3.64--> При выполнении команды npx eslint . ошибки линтинга должны отсутствовать.
- [x] <!--3.64--> В разделе scripts файла package.json:
  - [x] есть команда npm run start, которая запускает сервер на localhost:3000;
  - [x] и npm run dev, которая запускает сервер на localhost:3000 с хот релоудом.
- [x] <!--12.57--> Когда все зависимости установлены, приложение запускается командой npm run dev без ошибок.
- [x] <!--25.45--> Описанные роуты работают корректно:
  - [x] запрос на `GET /users/me` возвращает информацию о пользователе (email и имя);
  - [x] `PATCH /users/me` — обновляет информацию о пользователе;
  - [x] `GET /movies` — все сохранённые пользователем фильмы;
  - [x] `POST /movies` — создаёт фильм с переданными в теле данными;
  - [x] `DELETE /movies/movieId` — удаляет сохранённый фильмы по `_id`;
  - [x] `POST /signup` — создаёт пользователя с переданными в теле данными;
  - [x] `POST /signin` — возвращает JWT, если в теле запроса переданы правильные почта и пароль.
  - [x] Если вы сохраняете JWT в куках, роут `/signout` должен удалять JWT из куки.
- [x] <!--3.64--> Все роуты, кроме /signin и /signup, защищены авторизацией.

  Мидлвара для обработки неизвестного маршрута не закрыта авторизацией. Критерий засчитываю, но прошу исправить этот момент

- [x] <!--3.64--> Роуты пользователей и роуты фильмов описаны в отдельных файлах.
- [x] <!--3.64--> Ошибки API обрабатываются:
  - [x] если в запросе что-то не так, сервер возвращает ответ с ошибкой и её статусом;
  - [x] асинхронные обработчики завершены блоком catch;
  - [x] API не возвращает стандартных ошибок базы данных или Node.js.
- [x] <!--3.64--> В production-режиме адрес базы данных берётся из process.env.
- [x] <!--3.64--> Реализовано бережное хранение пароля:
  - [x] пароль хранится в зашифрованном виде;
  - [x] API не возвращает хеш пароля клиенту.
- [x] <!--3.64--> Данные валидируются перед добавлением в базу.

   В поле password для пользователя хранится хэш-пароля, поэтому валидировать его на уровне БД на то, что он является сложным паролем не имеет смысла

- [x] <!--3.64--> Пользователь не может удалить сохранённую карточку из профиля другого пользователя.
- [x] <!--3.64--> К серверу можно обратиться по https по адресу домена, указанному в README.md. 
- [x] <!--3.64--> Правильно реализовано хранение секретного ключа для создания JWT:
  - [x] для продакшн сборки он хранится в .env файле — этот файл не добавляется в git;
  - [x] в режиме разработки (при process.env.NODE_ENV !== 'production') код запускается и работает и без .env файла.

### Хорошие практики
- [x] <!--1.5--> Асинхронные операции реализованы промисами или async/await.
- [x] <!--1.5--> Запрос валидируется перед передачей контроллеру. Тело и, где необходимо, заголовки и параметры, проверяются по соответствующим схемам. Если запрос не соответствует схеме, обработка не передаётся контроллеру, и клиент получает ошибку валидации.
 
  В задании отсутствует ограничение на длину пароля
 
- [ ] <!--1.5--> Настроено логгирование:
  - [x] запросы и ответы записываются в файл request.log;
  - [ ] ошибки записываются в файл error.log;
    Для некоторых исключений в качестве параметра вместо строки передается объект из-за чего текст данных ошибок не логгируется
    https://i.imgur.com/djU0tma.png
  - [x] файлы логов не добавляются в репозиторий.
- [x] <!--1.5--> Ошибки обрабатываются централизованным обработчиком.
- [x] <!--1.5--> Централизованный обработчик ошибок описан в отдельном модуле.
- [x] <!--1.5--> В случае ошибки API возвращает статус ответа, который соответствует типу ошибки.
- [x] <!--1.5--> К серверу можно обратиться по https по адресу домена, указанному в README.md.
- [x] <!--1.5--> API приложения располагается на домене вида: name.zone/api, а не просто name.zone
- [x] <!--1.5--> Все роуты подключены в файле index.js, который находится в папке routes. Оттуда единый роут подключается в файле app.js.
### Рекомендации
- [x] <!--0.83--> Для ошибок API созданы классы, расширяющие конструктор Error.
- [x] <!--0.83--> Используется модуль Helmet для установки заголовков, связанных с безопасностью.
- [x] <!--0.83--> Конфигурация и константы в отдельных файлах:
  - [x] адрес Mongo-сервера в режиме разработки вынесен в отдельный конфигурационный файл;
  - [x] константы приложения — сообщения ответов и ошибок — вынесены в отдельный файл с константами.
- [x] <!--0.83--> Настроен rate limiter: число запросов с одного IP в единицу времени ограничено.
- [x] <!--0.83--> rate limiter сконфигурирован в отдельном файле и импортируется в app.js
- [x] <!--0.83--> API размещено на отдельном поддомене, например: api.news-explorer.tk.

## Количество баллов: 99


## Доп. комментарии
- В поле password модели пользователя хранится хэш-пароля, поэтому валидировать его на уровне БД на то, что он является сложным паролем не имеет смысла

2021-04-23 21:03 UTC, merged